### ISSUE TITLE
Add support for rpm/yum based distros to directory-bootstrap

### ISSUE THREAD

**Issue by hartwork** [hartwork/image-bootstrap#14]
References:
- https://github.com/dozzie/yumbootstrap
- http://prefetch.net/articles/yumchrootlinux.html
- http://www.lucas-nussbaum.net/blog/?p=385
- https://rwmj.wordpress.com/2009/03/05/fedora-equivalent-of-debootstrap/
- https://fedorahosted.org/mock/

**Comment by nplanel** [comment]
The list of Fedora, RHEL ... images are here : https://www.rdoproject.org/resources/image-resources/

I think they use https://github.com/rcbops/oz-image-build as image builder

**Comment by hurricanehrndz** [comment]
fedora should use groupinstall core for the bootstrap

**Comment by hurricanehrndz** [comment]
has fedora been tested?

**Comment by hartwork** [comment]
It worked for Fedora 25 at some point. Broken now? Please keep in mind image-boostrap is working with often moving targets.

**Comment by hurricanehrndz** [comment]
Okay, doesn't seem to work anymore with either 25 or 26. Does work with 21.

**Comment by hartwork** [comment]
I just tested Fedora 25 successfully from Git HEAD over here:
```
# directory-bootstrap fedora --release 25 fedora_25_chroot                                                                                                
[..]
# sudo pychroot fedora_25_chroot/ cat /etc/system-release
Fedora release 25 (Twenty Five)
```
If it doesn't work for you, please run with `--debug` and report a bug as a new ticket.

**Comment by hurricanehrndz** [comment]
@hartwork thanks for the quick feedback, what is your host os?

**Comment by hartwork** [comment]
Gentoo Linux most of the time and right now, and some Debian.

**Comment by hurricanehrndz** [comment]
Okay, I will try from another distro, because when I tried from openSUSE I got some sort of yum transaction check error with systemd and libc6. I don't think it has anything to do with the project, I tried the yum commands myself and got the same result. Thanks for looking into it for me.

**Comment by hartwork** [comment]
Closing, implemented a while ago.
