### ISSUE TITLE
Varying file sizes for Arch Linux images

### ISSUE THREAD

**Issue by kevin-olbrich** [hartwork/image-bootstrap#28]
Why are Arch Linux daily images varying in size?

Some images are ~500MB, some 1.1GB (with only one day between the builds).

Source: http://linuximages.de/openstack/arch/

**Comment by hartwork** [comment]
My guess would be that the small ones are broken.
I found that disk space run out on linuximages.de. I made space and deleted the small ones. Thanks for the report.

**Comment by hartwork** [comment]
PS: There should be new images of today in no more than an hour from now.
