### ISSUE TITLE
Failure to run on ubuntu 15.04/vivid due to kpartx lacking -u flag

### ISSUE THREAD

**Issue by dafstone** [hartwork/image-bootstrap#30]
Hi - 

I'm trying image-bootstrap out to bootstrap an arch system from Ubuntu 15, with a plain block device.

I'm getting a failure on the kpartx command as follows:

`Error: Command "kpartx -u -s /dev/sdd" returned non-zero exit status 1`

Having looked into this a little, kpartx doesn't actually have the -u (update partitions) flag on Ubuntu, which I expect is why it's having a failed exit. 

Full output below:

```

root@<server>:/home/<user>/host/image-bootstrap# ./image-bootstrap --bootloader none --password-file root_password.txt arch /dev/sdd
     _                          __             __      __               
    (_)_ _  ___ ____ ____  ___ / /  ___  ___  / /____ / /________ ____  
   / /  ' \/ _ `/ _ `/ -_)/__// _ \/ _ \/ _ \/ __(_-</ __/ __/ _ `/ _ \ 
  /_/_/_/_/\_,_/\_, /\__/    /_.__/\___/\___/\__/___/\__/_/  \_,_/ .__/ 
               /___/                      v0.9.1 :: 2015-07-11  /_/     

Software libre licensed under AGPL v3 or later.
Brought to you by Sebastian Pipping <sebastian@pipping.org>.
Please report bugs at https://github.com/hartwork/image-bootstrap.  Thank you!

Checking for blkid... /sbin/blkid
Checking for blockdev... /sbin/blockdev
Checking for chmod... /bin/chmod
Checking for chroot... /usr/sbin/chroot
Checking for cp... /bin/cp
Checking for find... /usr/bin/find
Checking for gpg... /usr/bin/gpg
Checking for kpartx... /sbin/kpartx
Checking for mkdir... /bin/mkdir
Checking for mkfs.ext4... /sbin/mkfs.ext4
Checking for mount... /bin/mount
Checking for parted... /sbin/parted
Checking for partprobe... /sbin/partprobe
Checking for rm... /bin/rm
Checking for rmdir... /bin/rmdir
Checking for sed... /bin/sed
Checking for tune2fs... /sbin/tune2fs
Checking for umount... /bin/umount
Checking for wget... /usr/bin/wget

Checking for known unsupported architecture/machine combination...
Checking if "/dev/sdd" is a block device...
Reading root password from file "/home/stone/host/image-bootstrap/root_password.txt"...
Unsharing Linux namespaces (mount, UTS/hostname)...
Checking size of "/dev/sdd"...
Partitioning "/dev/sdd"...
Activating partition devices...
Error: Command "kpartx -u -s /dev/sdd" returned non-zero exit status 1
If this looks like a bug to you, please file a report at https://github.com/hartwork/image-bootstrap.  Thank you!

```

**Comment by hartwork** [comment]
Hi! Interesting!

Ubuntu 15 sounds rather recent. Strange.

Thoughts on possible roads to go:
* Figure out, why `-u` is missing on Ubuntu (but not on Debian?)
* Figure out, if `-u` is essential or can be replaced in `image-bootstrap`
* Add a check to `image-bootstrap` to catch trouble upfront

Any help is welcome.

**Comment by dafstone** [comment]
All great roads - 

I did some digging into the provenance of the -u flag in kpartx and it seems that it was added 11 months ago to multipath-tools.  This means, I guess it's not in the 0.4.9-3 line, and apparently not in older versions of 0.5 either, as that release was tagged 2 years ago.  I think this may be a place where it just hasn't moved forward in Ubuntu. I don't use debian directly, but I'm not sure it's in as recently as jessie either, as I just looked up the line that matches the flags in the `multipath-tools` source, and there's no `u` option in there.

Here's that commit: http://git.opensvc.com/gitweb.cgi?p=multipath-tools/.git;a=commit;h=98cbca1773eec5d740bb0c441b27383c75a30449

Here's the jessie source for multipath tools:  http://anonscm.debian.org/cgit/pkg-lvm/multipath-tools.git/tree/multipath/main.c?h=jessie - note the lack of a 'u' option on line 436.

Assuming I understand what I'm seeing, which I might not as I'm not a C programmer, nor do I often dig into source trees outside of Github, Bitbucket, or the CLI - but I feel pretty confident that this change is really recent to multipart-tools/kpartx

Incidentally, the specific package version is `0.4.9-3ubuntu12`.  Here's the changelog from 15.04: https://launchpad.net/ubuntu/+source/multipath-tools/0.4.9-3ubuntu12.15.04.2

As for parts two and three, I'm not sure how much help I can be as I'm not a particularly good python programmer, but happy to help.  I think the concept for this tool is great, and though I'm just trying to use it to bootstrap arch on a sunday afternoon personally project, I can see how it could be really helpful in my regular work. 

Thanks!

**Comment by hartwork** [comment]
Hi!

On the commit, I think there is a mix-up with files here. The kpartx sources seem to be `kpartx/kpartx.c`. I found the addition of `-u` to kpartx at http://git.opensvc.com/gitweb.cgi?p=multipath-tools/.git;a=commit;h=223a44725ce916de4070ceec1b28e213ac593acb but that doesn't seem to be included with 0.4.9-3ubuntu12 of Ubuntu vivid, either.

For image-bootstrap, I am wondering now: why not just use plain `-a`, instead.

Best, Sebastian

**Comment by hartwork** [comment]
I am confident that the commit above works around the issue. If it doesn't, please report back and re-open the ticket. Thanks!

**Comment by dafstone** [comment]
Fantastic - I'll give it a try this weekend, and will report back.  Thanks for looking at this!
