### ISSUE TITLE
cloud-init seems to not configure the network nameserver

### ISSUE THREAD

**Issue by nplanel** [hartwork/image-bootstrap#32]
/etc/resolv.conf still have the static configuration from the image after boot.

Tested with latest Arch Linux image 02032016

**Comment by hartwork** [comment]
Maybe that's a configuration thing, needs a closer look at cloud-init. Also, I wanted to re-think when to leave or delete the file during finalization.

**Comment by hartwork** [comment]
Ticket #23 is related.

**Comment by hartwork** [comment]
Fixed in Git, image 2016-08-30-13-47 and after contain the fix.
