### ISSUE TITLE
Arch OpenStack images no longer resize first partition to full disk size

### ISSUE THREAD

**Issue by watermelonjuice** [hartwork/image-bootstrap#34]
Your current image only mounts a 2gb partition. It make it a pain to boot into rescue mode and resize it. Any reason it's setup like this? Wouldn't it be better to just mount the full available space?

**Comment by hartwork** [comment]
In context of OpenStack, the partition _should_ be resized to all available space, _already_.
Maybe it broke in the meantime.
Please elaborate on your setup and so on. Thanks!

**Comment by watermelonjuice** [comment]
I'm using OVH's public cloud. The last image I checked was on August 20 from linuximages.de. I experienced the same issue with multiple images from earlier dates. Let me test with latest to see if the issue is still there. Meanwhile, let me know what you need to know about OVH's setup.

**Comment by hartwork** [comment]
I just re-checked: First and only partition is resized for me.
What I did (may not be `/dev/loop0` for you!):
```
sudo truncate --size 5g /tmp/5g
sudo losetup --show -f /tmp/5g
sudo ./image-bootstrap --debug --verbose --openstack --password .... arch /dev/loop0
sudo losetup --show -f /tmp/5g
sudo qemu-system-x86_64 -hda /dev/loop0
```
The log-in as root, password `....`, run `lsblk`: `sda1` takes 5G, i.e. got resized. Not?

**Comment by hartwork** [comment]
Closing, please feel free to re-open if needed.

**Comment by watermelonjuice** [comment]
Hi, sorry for the delayed response. Was travelling.

I just tested it again: 
[arch@dev1 ~]$ df
Filesystem     1K-blocks   Used Available Use% Mounted on
dev               991056      0    991056   0% /dev
run              1002080    348   1001732   1% /run
/dev/vda1        2030416 958588    950640  51% /
tmpfs            1002080      0   1002080   0% /dev/shm
tmpfs            1002080      0   1002080   0% /sys/fs/cgroup
tmpfs            1002080      0   1002080   0% /tmp
tmpfs             200416      0    200416   0% /run/user/1000
[arch@dev1 ~]$ wget http://linuximages.de/openstack/arch/arch-openstack-LATEST-image-bootstrap.qcow2
--2016-09-11 11:04:40--  http://linuximages.de/openstack/arch/arch-openstack-LATEST-image-bootstrap.qcow2
Resolving linuximages.de (linuximages.de)... 5.102.147.58
Connecting to linuximages.de (linuximages.de)|5.102.147.58|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1262944256 (1.2G) [application/octet-stream]
Saving to: 'arch-openstack-LATEST-image-bootstrap.qcow2'

arch-openstack-LATEST-ima  76%[============================>         ] 925.40M  11.6MB/s    in 82s     s


Cannot write to 'arch-openstack-LATEST-image-bootstrap.qcow2' (No space left on device).
[arch@dev1 ~]$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
dev               991056       0    991056   0% /dev
run              1002080     348   1001732   1% /run
/dev/vda1        2030416 1909228         0 100% /
tmpfs            1002080       0   1002080   0% /dev/shm
tmpfs            1002080       0   1002080   0% /sys/fs/cgroup
tmpfs            1002080       0   1002080   0% /tmp
tmpfs             200416       0    200416   0% /run/user/1000

**Comment by hartwork** [comment]
`/dev/vda1` of that `dev1` has 2GiB total only, yes. The question is:
* How did you generate that `dev1` machine
* How much space does the *outside* disk have; it matches  `/dev/vda` without "1" inside the machine

**Comment by watermelonjuice** [comment]
It was created using OVH's public cloud interface. I uploaded the image using the following command:
glance image-create --property hypervisor_type=qemu --name "Arch Latest" --file arch-openstack-LATEST-image-bootstrap.qcow2 --disk-format qcow2 --container-format bare

It has 10GB. So far what I have been doing is booting the image into rescue mode and using fdisk to resize the partition.

**Comment by hartwork** [comment]
For a quick reply: I can confirm the issue now. Stay tuned.

**Comment by hartwork** [comment]
For the record, my steps to reproduce above were not sufficient earlier (as they lacked post-installation growths of the disk). A proper (and more flexible) version would be:
```
#! /bin/bash
PS4='# '
set -e
set -x

# Setup
regular="$(mktemp)"
truncate --size 2g "${regular}"
device="$(sudo losetup --show -f "${regular}")"
sudo ./image-bootstrap --debug --verbose --openstack --password .... arch "${device}"

# Resize
sleep 2
sudo losetup -d "${device}"
sleep 2
truncate --size 3g "${regular}"
device="$(sudo losetup --show -f "${regular}")"
sleep 2
sudo partx -d "${device}"

# Inspect
sudo qemu-system-x86_64 -hda "${device}" || true

# Teardown
sleep 2
sudo losetup -d "${device}"
sleep 2
rm -v "${regular}"
```

**Comment by hartwork** [comment]
> So far what I have been doing is booting the image into rescue mode and using fdisk to resize the partition.

For a quicker workaround, you can use `growpart /dev/vda 1` right from a non-rescue boot.
Demo:
![growpart_demo](https://cloud.githubusercontent.com/assets/1577132/18418142/46be0ad6-7841-11e6-8f3a-526561773a15.png)

**Comment by hartwork** [comment]
@watermelonjuice, could you give image
[arch-openstack-2016-09-11-17-26-image-bootstrap-0.9.1-80-g14439d4.qcow2](http://linuximages.de/openstack/arch/arch-openstack-2016-09-11-17-26-image-bootstrap-0.9.1-80-g14439d4.qcow2)
(with commit 14439d421853e28f2048fd6eac7c70686b9d1b0b applied) a try?

Thank you!

**Comment by watermelonjuice** [comment]
Its working but hostname is not taken from openstack anymore.

**Comment by hartwork** [comment]
My guess is that cloud-init in Arch was at 0.7.6 before and became 0.7.7 recently. Regarding image-bootstrap there is more to adapt now, e.g. cloud-init calls out to netctl now which breaks networking as set up by image-bootstrap, currently. So it will take more time to get things back to work, I'm afraid.
If hostname support is important to you, please open a dedicated ticket so it doesn't get lost.
Also, I explicitly welcome help with debugging.

**Comment by hartwork** [comment]
> Its working [..].

Thanks for testing!
