### ISSUE TITLE
cloud-init datasources does not include the "NoCloud" ds, causing issues when using a CDROM drive to provide metadata

### ISSUE THREAD

**Issue by efenex** [hartwork/image-bootstrap#36]
When creating a VM using KVM/Libvirt, it is common practice to attach an iso image with configuration data for cloud-init. In order for this to work, the "NoCloud" data source needs to be enabled.

From a (working) ubuntu image, the following cloud-init configuration is configured in /etc/cloud/cloud.cfg.d/90_dpkg.cfg:

datasource_list: [ NoCloud, ConfigDrive, OpenNebula, Azure, AltCloud, OVF, MAAS, GCE, OpenStack, CloudSigma, SmartOS, Ec2, CloudStack, None ]

In this archlinux image, the file is called /etc/cloud/cloud.cfg.d/90_datasource.cfg and should be expanded to include at least the NoCloud directive (potentially the others too).

**Comment by hartwork** [comment]
Thanks for the report!

Due to recent changes in Arch Linux, generation of Arch OpenStack images is broken with other regards already. I have plans to fix it and will consider your proposal.

**Comment by jonhoo** [comment]
@efenex are you sure `NoCloud` is needed for the ISO image configuration? I'm pretty sure only `CloudDrive` is necessary for that to work...

**Comment by jonhoo** [comment]
Never mind me. `ConfigDrive`, while similar, is likely not what you want during testing, as it requires a [more sophisticated](https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html) disk layout. I also vote for `NoCloud` being added to the list.

**Comment by hartwork** [comment]
Fixed by #63.
