### ISSUE TITLE
LinuxImages no longer creating new Arch images daily

### ISSUE THREAD

**Issue by watermelonjuice** [hartwork/image-bootstrap#37]
Hi

It seems like http://linuximages.de/openstack/arch/ stopped creating new Arch images. I don't know if this is intentional. 

I am also having an issue with the latest image that cloud-init is failing to install the ssh key and as such there is no way to get the logs and see what went wrong without access to the host. I am attempting to use the image on OVH public cloud.

**Comment by hartwork** [comment]
Hi!

It's not intentional but as Arch is a living thing they made changes that (technically speaking) broke image-bootstrap Arch image generation as working previously, e.g. they moved to cloud-init >=0.7.7 (which is a good thing through glasses of progress). I haven't found time to adapt to these (non-trivial) changes yet and I also lack a proper OpenStack testbed setup right now. If you want to team up on getting Arch image generation back in shape, that would be welcome. There is two sides to it: (1) manually figuring out how to get things back to work (especially changes that happened to networking) and then (2) adjusting what image-bootstrap does. If you can help with (1), I can do (2) soon.

Best, Sebastian

**Comment by jonhoo** [comment]
The `cloud-init` package is currently pretty horribly broken in Arch. You should wait for `0.7.8-3`, which is in [`[community-testing]`](https://www.archlinux.org/packages/community-testing/any/cloud-init/), as that fixes all the dependency issues the current version has.

**Comment by jonhoo** [comment]
See also https://github.com/jonhoo/cloud-arch/blob/master/bootstrap.sh#L36

**Comment by hartwork** [comment]
image-bootstrap installs extra dependencies on top already (https://github.com/hartwork/image-bootstrap/blob/master/image_bootstrap/distros/arch.py#L245). Extending that list would be easy. The changes in cloud-init and it's interaction with some (new?) systemd networking frontend ([netctl](https://wiki.archlinux.org/index.php/netctl) AFAIR) are more difficult to handle.

I'd be interested to learn about the most clean and safe way (meaning SSL downloads and binaries from Arch core devs only) to install cloud-init 0.7.6 (and/or 0.7.8). Any ideas?

**Comment by hartwork** [comment]
I made it use cloud-init 0.7.**6** again for now.
Please give the latest image (http://linuximages.de/openstack/arch/arch-openstack-2016-11-18-00-43-image-bootstrap-0.9.1-83-g994f96c.qcow2 as of this writing) a spin and let me know if it works. Cheers!

**Comment by watermelonjuice** [comment]
Tried the latest it seems to be working fine. What kind of testing infrastructure do you need? I have reached out to OVH staff who use your image to see if they can give you any free infrastructure.

**Comment by hartwork** [comment]
Working fine sounds great to me. I'll close this ticket then.
For a testbed I would need a way to create images on some host machine and be able to give them a testspin (1) without uploading them somewhere for minutes and (2) in a setup with realistic input to cloud-init from an actual OpenStack setup. But let's take that off-ticket. My profile page has my address, if you want to CC me on something later.
Best, Sebastian

**Comment by watermelonjuice** [comment]
No new images since July.

**Comment by hartwork** [comment]
@watermelonjuice Issue #43 is blocking new images, a bug in Arch to my best knowledge, see first comment on that ticket. Please comment at #43 if you have ideas for a fix.

**Comment by hartwork** [comment]
@watermelonjuice Tried a new idea, seems fixed now. Latest Arch image now is of today and I hope for daily builds be back at work.
