### ISSUE TITLE
[Fedora] directory-bootstrap does not support --arch parameter?

### ISSUE THREAD

**Issue by mdeguzis** [hartwork/image-bootstrap#40]
Why is it not possible to provide the arch for this script but you can for image-bootstrap?

**Comment by hartwork** [comment]
There was no need so far. Is this a feature request?

**Comment by mdeguzis** [comment]
Yes it can be tagged as such.

**Comment by hartwork** [comment]
Forget that, I had another look. It's there, but not at the top level, at least for arch and gentoo.
```
# ./directory-bootstrap arch --help
usage: directory-bootstrap arch [-h] [--arch {i686,x86_64}]
                                [--image-date YYYY-MM-DD] [--mirror URL]

optional arguments:
  -h, --help            show this help message and exit
  --arch {i686,x86_64}  architecture (e.g. x86_64)
  --image-date YYYY-MM-DD
                        date to use boostrap image of (e.g. 2015-05-01,
                        default: latest available)
  --mirror URL          pacman mirror to use (default:
                        http://mirror.rackspace.com/archlinux/$repo/os/$arch)
```
For which distro do you need it? Implementation differs across distros.

**Comment by hartwork** [comment]
Support for Fedora [is broken](https://github.com/hartwork/image-bootstrap/runs/615921857#step:7:575) and would need an upgrade to DNF to have a future. DNF is not widely available though, e.g. Debian and Gentoo do not have a package for it. So broken support for creating Fedora chroots is about to be dropped.
