### ISSUE TITLE
Add support for generating Alpine Linux OpenStack images

### ISSUE THREAD

**Issue by jonhoo** [hartwork/image-bootstrap#41]
It'd be really near if `image-bootstrap` also supported generating images for [Alpine Linux](https://www.alpinelinux.org/), as it is a distro that is specifically designed to be small and secure (and therefore fits well as a cloud image). They also have `cloud-init` available as a [package](https://pkgs.alpinelinux.org/package/edge/testing/x86/cloud-init).

What would be the changes necessary to add another distro to `image-bootstrap`? I might be able to contribute some time to this if I'm pointed in the right direction.

**Comment by jonhoo** [comment]
The [Alpine Docker image](https://github.com/gliderlabs/docker-alpine) may provide some useful insights too.

**Comment by hartwork** [comment]
Hi Jon,

a key question is if Alpine has some equivalent to `debootstrap`/`directory-bootstrap` already or if that part needs to be made as well. Do they have a tool for Alpine chroot creation?

**Comment by jonhoo** [comment]
Not that I know of — we'd likely have to implement a chroot procedure similar to the one used for [arch](https://github.com/hartwork/image-bootstrap/blob/master/directory_bootstrap/distros/arch.py)

**Comment by hartwork** [comment]
Can you do the research on what's needed?

**Comment by jonhoo** [comment]
I'll take a look and report back.

**Comment by jonhoo** [comment]
Ah, interesting... So, looking at the [Docker `mkimage-alpine`](https://github.com/moby/moby/blob/master/contrib/mkimage-alpine.sh), Alpine Linux provides a statically linked binary of their package manager that can bootstrap the system. It's fetched [here](https://github.com/moby/moby/blob/master/contrib/mkimage-alpine.sh#L27) and invoked [here](https://github.com/moby/moby/blob/master/contrib/mkimage-alpine.sh#L32). This procedure is documented in the official [Alpine wiki](https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot). There is even an official [`alpine-chroot-install`](https://github.com/alpinelinux/alpine-chroot-install/) script that may be of use. My guess is that we can also use parts of the included [`setup-alpine`](https://wiki.alpinelinux.org/wiki/Setup-alpine) script to finalize setup.

**Comment by hartwork** [comment]
Hi!

Some of these options look good, for some I have concerns:
* Moby/[mkimage-alpine.sh](https://github.com/moby/moby/blob/master/contrib/mkimage-alpine.sh) is by Moby, not by Alpine itself. I would expect the user to trust alpine code if he/she wants to bootstrap Alpine but nothing else, so not Moby (even if they're the best)
* [Installing Alpine Linux in a chroot](https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot) looks excellent
* [alpine-chroot-install](https://github.com/alpinelinux/alpine-chroot-install/) may do modifications to the host system, e.g. installing packages. If you search for "host", you find plenty. I'm not sure if that's cool for something to download and execute. On the other hand, if that exists maybe there is no point in duplicating all of that.

What do you think?

**Comment by jonhoo** [comment]
Looking through the `alpine-chroot-install` script, it seems like all it's really doing is installing QEMU (which is the only reason it modifies the host afaict) and then following the "installing Alpine Linux in a chroot" wiki entry, so I think just following those steps is the way to go.

**Comment by ainriver** [comment]
@jonhoo The `alpine-chroot-install` script is not strictly necessary. The qemu installation is for cross-architecture installs, which is not intended to be implemented for now.

**Comment by hartwork** [comment]
Quick update regarding *`directory`*`-bootstrap`: Basic support for Alpine Linux just arrived. It downloads the latest mini chroot tarball, verifies its signature, and extracts the tarball.

**Comment by hartwork** [comment]
Closing as "not happening without a sponsor". If a company needs this feature enough to be a sponsor, please reach out via the e-mail address in my profile :pray: Not that this includes review of related pull requests.
