### ISSUE TITLE
grub install fails on EFI systems

### ISSUE THREAD

**Issue by jonhoo** [hartwork/image-bootstrap#42]
I'm trying to construct an Arch Linux image from an Arch Linux host, and am running into some issue on the step that installs the bootloader. I first tried `host-extlinux`, which completed successfully, but resulted in an unbootable image. I then tried `auto`, which failed with a suspicious-looking:
```console
Error: Command "chroot /mnt/tmp5bDk0h grub-install \(hd9999\)" returned non-zero exit status 1
```
I then finally went with `host-grub2-device`, which also errors, though with a slightly different error:
```console
$ sudo image-bootstrap --hostname foobar --openstack --bootloader host-grub2-device arch $LOOP_DEVICE
     _                          __             __      __
    (_)_ _  ___ ____ ____  ___ / /  ___  ___  / /____ / /________ ____
   / /  ' \/ _ `/ _ `/ -_)/__// _ \/ _ \/ _ \/ __(_-</ __/ __/ _ `/ _ \
  /_/_/_/_/\_,_/\_, /\__/    /_.__/\___/\___/\__/___/\__/_/  \_,_/ .__/
               /___/                    v0.9.2.1 :: 2017-01-10  /_/

...

Installing bootloader to device "/dev/loop0" (approach "host-grub2-device")...
Unmounting partitions...
Removing directory "/mnt/tmpzijoWx"...
Deactivating partition devices...
Error: Command "grub-install --boot-directory /mnt/tmpzijoWx/boot /dev/loop0" returned non-zero exit status 1
```
I then decided to try this command manually, and ran:
```console
$ sudo mkdir /mnt/tmpzijoWx
$ sudo mount /dev/loop0p1 /mnt/tmpzijoWx
$ sudo grub-install --boot-directory /mnt/tmpzijoWx/boot /dev/loop0
Installing for x86_64-efi platform.
grub-install: error: cannot find EFI directory.
```
So, it looks like GRUB (2.02) isn't super happy about trying to install itself onto a loop-mounted file-system, since it can't get at the necessary EFI variables. `host-grub2-drive` doesn't do much better:
```console
...

Writing device map to "/mnt/tmpmGKytg/boot/grub/device.map" (mapping "(hd9999)" to "/dev/loop0")...
Installing bootloader to device "/dev/loop0" (approach "host-grub2-drive")...
Unmounting partitions...
Removing directory "/mnt/tmpmGKytg"...
Deactivating partition devices...
Error: Command "grub-install --boot-directory /mnt/tmpmGKytg/boot \(hd9999\)" returned non-zero exit status 1
```

**Comment by jonhoo** [comment]
In case it's relevant, booting for the `host-extlinux` image fails with
```
Boot from hard disk...
MBR

SYSLINUX 6.03 EDD ...
Failed to load ldlinux.c32
```

**Comment by hartwork** [comment]
Hi!

I'l just braindump a few thoughts for the moment:
* The `grub-install` line does not contain any EFI parameters. Why does it operate in EFI mode? It didn't do that last time I checked. I think it's also not default in Debian, they have https://packages.debian.org/sid/grub-efi for that.
* I have never used image-bootstrap and EFI used together
* I wonder if the images on https://linuximages.de/openstack/arch/ (created on Debian) have the same problem by now. On a side note, they stopped building a few days ago. So that needs investigation anyway. Moving targets are crazy to cover, I suppose :)
* I can recommend `--verbose` to see program output and command lines.
* Having a closer look myself will need time.

**Comment by jonhoo** [comment]
I have the standard Arch `grub` package installed. It's `--help` suggests that EFI install is now the default:
```console
$ grub-install --version
grub-install (GRUB) 2.02
$ grub-install --help
Usage: grub-install [OPTION...] [OPTION] [INSTALL_DEVICE]
...
      --target=TARGET        install GRUB for TARGET platform
                             [default=x86_64-efi]; available targets: arm-efi,
                             arm-uboot, arm64-efi, i386-coreboot, i386-efi,
                             i386-ieee1275, i386-multiboot, i386-pc,
                             i386-qemu, i386-xen, ia64-efi, mips-arc,
                             mips-qemu_mips, mipsel-arc, mipsel-loongson,
                             mipsel-qemu_mips, powerpc-ieee1275,
                             sparc64-ieee1275, x86_64-efi, x86_64-xen
```
I'm not surprised that `image-bootstrap` + EFI doesn't work (I don't even know how it would, since it can't invoke `efibootmgr`). Unfortunately, it also doesn't seem like there's a non-efi target there anymore? It seems likely that the same issue is hitting the generated images. `--verbose` is good to know, but just gave the same error:
```console
...
Installing bootloader to device "/dev/loop0" (approach "host-grub2-device")...
# grub-install --boot-directory /mnt/tmpDhH0v3/boot /dev/loop0
Installing for x86_64-efi platform.
grub-install: error: cannot find EFI directory.
```

**Comment by jonhoo** [comment]
For what it's worth, the Arch Wiki [suggests](https://wiki.archlinux.org/index.php/GRUB#Installation):
```console
# grub-install --target=i386-pc /dev/sdx
```

**Comment by hartwork** [comment]
Hi!

Git master passes `--target=i386-pc` now.

The linuximages.de failure this: https://github.com/hartwork/image-bootstrap/issues/43
If you can help getting to the bottom of that, help is appreciated.

For extlinux I made this new ticket: https://github.com/hartwork/image-bootstrap/issues/44

Fix this very EFI ticket, is there anything left more to fix?

**Comment by jonhoo** [comment]
The image now both builds and boots correctly -- thanks!
Yes, I think this issue can then be closed.

As an aside, I put up an Arch Linux package for `image-bootstrap` at https://aur.archlinux.org/packages/image-bootstrap-git/. I'd appreciate if you could take a look to see if I missed something obvious. See in particular the [`PKGBUILD` file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=image-bootstrap-git).

**Comment by hartwork** [comment]
Thank you for `--target=i386-pc` and the AUR package. The dependencies look complete to me, good work.
