### ISSUE TITLE
Bootloader `host-extlinux` images not bootable on Arch

### ISSUE THREAD

**Issue by hartwork** [hartwork/image-bootstrap#44]
Host OS: Arch Linux
Guest OS: Arch Linux
Boot loader: `host-extlinux`
(Additional flags: `--openstack`)

During boot (from https://github.com/hartwork/image-bootstrap/issues/42#issuecomment-316208759):
```
Boot from hard disk...
MBR

SYSLINUX 6.03 EDD ...
Failed to load ldlinux.c32
```

**Comment by jonhoo** [comment]
I wonder if this is related to http://www.syslinux.org/wiki/index.php?title=Filesystem#ext, specifically:
> As of Syslinux 6.03, "pure 64-bits", compression and/or encryption are not supported.
> 
> Quoting part of the release notes of version 1.43 of e2fsprogs (May 17, 2016):
> > Mke2fs will now create file systems with the metadata_csum and 64bit features enabled by default.
> 
> Users should rather (manually) disable the 64bit feature in the mke2fs command when creating / formatting a boot volume with ext4; otherwise, the bootloader (as of version 6.03) will fail.

**Comment by jonhoo** [comment]
This is also supported by [this](https://wiki.archlinux.org/index.php/syslinux#Failed_to_load_ldlinux) troubleshooting entry on the Arch Wiki.

**Comment by hartwork** [comment]
Thanks for the research. Assuming that's what we have here (still need to try myself), how about this approach for a fix in general:

* Append `-O ^64bit` to `mkfs.ext4` command if bootloader is extlinux (and only then)
* Warn about it on stderr in the process (to make people aware and question their choice over GRUB)

?

**Comment by jonhoo** [comment]
That seems reasonable. I don't know if it's worth warning about, but sure. Personally I strongly dislike GRUB, and don't particularly care about whether I get 64-bit support on my VM FS, but I can also just ignore the warning :)

**Comment by hartwork** [comment]
I can confirm both issue and fix now. Pushed to `master` now.

**Comment by jonhoo** [comment]
Minor comment, but I'd break the warning into two lines after between the two sentences. Makes it wrap better on narrow terminals.

**Comment by hartwork** [comment]
Here you go. Thanks for the report and research again.
