### ISSUE TITLE
Cache images after initial bootstrap

### ISSUE THREAD

**Issue by jonhoo** [hartwork/image-bootstrap#46]
When generating many images, it is kind of sad to have to go through the full bootstrapping process multiple times. I believe it should be possible to cache the image that results from doing the initial distro bootstrap, and then generate new images from that subsequently. This should save significant time when building more than one image.

**Comment by hartwork** [comment]
Have you tried running with Polipo, Haveged and tmpfs for speeding things up?

A full Arch OpenStack (re-)run takes only 2 minutes for me (despite a rather crappy internet connection):
```console
# time sudo http_proxy=127.0.0.1:8123 ./image-bootstrap --openstack arch "${LOOP_DEV}"
[..]
Done.

real    2m6.562s
user    1m10.739s
sys     0m15.256s
```

**Comment by jonhoo** [comment]
Adding a proxy helps a little (I'm already building on tmpfs), but even 2 minutes per VM is pretty slow to me. I often have to re-build 7-10 VMs each time I do a re-build, which then takes a while. It's also a pain when debugging a new image. For comparison, [`cloud-arch`](https://github.com/jonhoo/cloud-arch) takes ~3 seconds to build a second (empty) VM image once any previous image has been built. It also doesn't require running a web proxy (since the full base image is cached).

**Comment by jonhoo** [comment]
One other point here is that a proxy's contents must also be persistent across invocations of `image-bootstrap` to have an effect.

**Comment by hartwork** [comment]
I need to pull the red card here: Way too much things to consider, quite a bit of work, no gain but runtime. I need this 0% myself and lose time for other things. I may consider a pull request, but only if added complexity is low (and I imagine quite some). Sorry.

**Comment by jonhoo** [comment]
For the record (and for someone who may wish to implement this): I *think* the way one would do this would be to save the entire loopback device state just before calling the pre/chroot/post scripts using a filename that's deterministically derived from the command-line arguments to `image-bootstrap`. That way, you just check if such a file exists at the beginning of execution, and if it does, mount that instead of an empty disk, and jump directly to where the scripts are executed.

**Comment by hartwork** [comment]
Also needed: Checking if the cache is older than X, making X configurable, checking for differences in invocation parameters that would cases differences.
