### ISSUE TITLE
Provide better errors when scripts fail

### ISSUE THREAD

**Issue by jonhoo** [hartwork/image-bootstrap#48]
Try creating an entirely empty file, mark it as executable, and add it to the `scripts-pre` directory. The resulting error is not particularly helpful:
```
...
Running pre-chroot scripts...
# /tmp/tmp.5v3QeEfQiI/pre/test.sh
Unmounting partitions...
# umount /mnt/tmpotamTf
Removing directory "/mnt/tmpotamTf"...
Deactivating partition devices...
# kpartx -d /dev/loop0
Error: [Errno 8] Exec format error
If this looks like a bug to you, please file a report at https://github.com/hartwork/image-bootstrap.  Thank you!
```

It'd be better if the error told you *which* script failed to execute in addition to the error. In this particular case it might also tell you that the file is missing a `#!` line at the beginning, but that's less important.

**Comment by hartwork** [comment]
Should be fixed.
