### ISSUE TITLE
Add another script execution phase

### ISSUE THREAD

**Issue by jonhoo** [hartwork/image-bootstrap#54]
Currently, we have `pre`, `chroot`, and `post`. `pre` gets executed before the `chroot` is constructed and many utilities (such as `sudo`) have been installed, `chroot` gets executed inside `$MNTPOINT` once all other setup has finished, and `post` gets executed at the end outside of the `$MNTPOINT`. This leaves one important hook for scripts: outside the after all other setup has completed (i.e., *just* before the `chroot` scripts run). I was expecting `pre` to be like this, but was surprised when it wasn't. In particular, where `pre` currently runs, many commands do not work since the various special partitions haven't been mounted, the package manager hasn't been initialized, etc.

**Comment by hartwork** [comment]
What would be examples of adjustments that need to be done after `pre` but before/outside `chroot`?
Keep in mind that symlinks in chroots make operation without changing into it rather dangerous, in general.

**Comment by jonhoo** [comment]
Never mind, I found a workaround :)
