### ISSUE TITLE
Error: hostname 'sources.archlinux.org' doesn't match 'archive.archlinux.org' with Python <2.7.9

### ISSUE THREAD

**Issue by danst0** [hartwork/image-bootstrap#60]
Hi,

I get this error message when trying to bootstrap arch from an Ubuntu system:
Error: hostname 'sources.archlinux.org' doesn't match 'archive.archlinux.org'

> ```
> d:~$ sudo image-bootstrap arch --mirror http://mirror.hactar.xyz/$repo/os/$arch /dev/sdb
>      _                          __             __      __               
>     (_)_ _  ___ ____ ____  ___ / /  ___  ___  / /____ / /________ ____  
>    / /  ' \/ _ `/ _ `/ -_)/__// _ \/ _ \/ _ \/ __(_-</ __/ __/ _ `/ _ \ 
>   /_/_/_/_/\_,_/\_, /\__/    /_.__/\___/\___/\__/___/\__/_/  \_,_/ .__/ 
>                /___/                    v0.9.2.1 :: 2017-01-10  /_/     
> 
> Software libre licensed under AGPL v3 or later.
> Brought to you by Sebastian Pipping <sebastian@pipping.org>.
> Please report bugs at https://github.com/hartwork/image-bootstrap.  Thank you!
> 
> Selected approach "chroot-grub2-drive" for bootloader installation.
> Checking for blkid... /sbin/blkid
> Checking for blockdev... /sbin/blockdev
> Checking for chmod... /bin/chmod
> Checking for chroot... /usr/sbin/chroot
> Checking for cp... /bin/cp
> Checking for find... /usr/bin/find
> Checking for gpg... /usr/bin/gpg
> Checking for kpartx... /sbin/kpartx
> Checking for mkdir... /bin/mkdir
> Checking for mkfs.ext4... /sbin/mkfs.ext4
> Checking for mount... /bin/mount
> Checking for parted... /sbin/parted
> Checking for partprobe... /sbin/partprobe
> Checking for rm... /bin/rm
> Checking for rmdir... /bin/rmdir
> Checking for sed... /bin/sed
> Checking for tune2fs... /sbin/tune2fs
> Checking for umount... /bin/umount
> Checking for wget... /usr/bin/wget
> 
> Checking for known unsupported architecture/machine combination...
> Checking if "/dev/sdb" is a block device...
> Unsharing Linux namespaces (mount, UTS/hostname)...
> Checking size of "/dev/sdb"...
> Partitioning "/dev/sdb"...
> Activating partition devices...
> Creating file system on "/dev/mapper/sdb1"...
> Creating directory "/mnt/tmproV0B_"...
> Mounting partitions...
> Creating directory "/mnt/tmproV0B_/etc"...
> Writing file "/mnt/tmproV0B_/etc/hostname"...
> Writing file "/mnt/tmproV0B_/etc/resolv.conf" (based on file "/etc/resolv.conf")...
> Bootstrapping Arch into "/mnt/tmproV0B_"...
> Checking access to "/var/cache/directory-bootstrap"...
> Checking access to "/mnt/tmproV0B_"...
> Downloading image listing...
> Downloading keyring listing...
> Cleaning up "/tmp/tmpsTVFde"...
> Unmounting partitions...
> Removing directory "/mnt/tmproV0B_"...
> Deactivating partition devices...
> Error: hostname 'sources.archlinux.org' doesn't match 'archive.archlinux.org'
> If this looks like a bug to you, please file a report at https://github.com/hartwork/image-bootstrap.  
> ```
Thank you!

**Comment by hartwork** [comment]
Hi!

I cannot confirm the error so far (neither with `--mirror http://mirror.hactar.xyz/staging/os/x86_64/` nor without). Does it still occur? Can you share the interpolated URL and add `--verbose`/`--debug` to the4 command if it shows again?

**Comment by danst0** [comment]
--debug results in:

> ...
> Unmounting partitions...
> Removing directory "/mnt/tmpZCYZ2O"...
> Deactivating partition devices...
> Traceback (most recent call last):
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
>     main_function(messenger, options)
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/cli.py", line 93, in _main__level_three
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 927, in run
>     self.run_directory_bootstrap()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 420, in run_directory_bootstrap
>     self._config.bootloader_approach,
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/distros/arch.py", line 76, in run_directory_bootstrap
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 263, in run
>     keyring_listing_html = self._get_keyring_listing()
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 74, in _get_keyring_listing
>     return self.get_url_content('https://sources.archlinux.org/other/archlinux-keyring/')
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/base.py", line 96, in get_url_content
>     return requests.get(url).text
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
>     return request('get', url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
>     raise SSLError(e)
> SSLError: hostname 'sources.archlinux.org' doesn't match 'archive.archlinux.org'
> Error: hostname 'sources.archlinux.org' doesn't match 'archive.archlinux.org'
> 
>

**Comment by hartwork** [comment]
You have no relatad magic in `/etc/hosts`, right?
No proxy in `http_proxy` or something?

It seems like the same IP (88.198.91.70) named `orion.archlinux.org` is serving both hosts. Not sure where the name is mixed up. I wonder if it could be a requests version issue. This is how I checked two versions of request on my local machine:
```console
# cd "$(mktemp -d)"
# virtualenv issue60
# source issue60/bin/activate
# pip install 'requests==2.18.4'
# python2 -c 'import requests; print(requests.__version__); v = requests.get("https://sources.archlinux.org/other/archlinux-keyring/").text'
2.18.4
# pip install 'requests==2.14.2'
# python2 -c 'import requests; print(requests.__version__); v = requests.get("https://sources.archlinux.org/other/archlinux-keyring/").text'
2.14.2
```
Any other ideas?

**Comment by danst0** [comment]
This might be the answer: http://docs.python-requests.org/en/master/community/faq/
My python is 2.7.6 I am upgrading now.

**Comment by danst0** [comment]
After the upgrade I get the error:

> Downloading keyring listing...
> Re-using cache file "/var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz.sig".
> Re-using cache file "/var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz".
> Initializing temporary GnuPG home at "/tmp/tmpDxUMMn/gpg_home"...
> Downloading "https://sks-keyservers.net/sks-keyservers.netCA.pem"...
> Importing GPG keys whitelisted to sign archlinux-keyring...
> Cleaning up "/tmp/tmpDxUMMn"...
> Unmounting partitions...
> Removing directory "/mnt/tmpAk7lny"...
> Deactivating partition devices...
> Traceback (most recent call last):
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
>     main_function(messenger, options)
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/cli.py", line 93, in _main__level_three
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 927, in run
>     self.run_directory_bootstrap()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 420, in run_directory_bootstrap
>     self._config.bootloader_approach,
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/distros/arch.py", line 76, in run_directory_bootstrap
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 278, in run
>     'BD84DE71F493DF6814B0167254EDC91609BC9183',  # Christian Hesse <Christi@n-Hes.se>
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 149, in _import_gpg_keys
>     self._executor.check_call(cmd)
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/executor.py", line 23, in check_call
>     cwd=cwd,
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['unshare', '--fork', '--pid', 'gpg', '--home', '/tmp/tmpDxUMMn/gpg_home', '--keyid-format', '0xlong', '--batch', '--receive-keys', '4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC']' returned non-zero exit status 2
> Error: Command "unshare --fork --pid gpg --home /tmp/tmpDxUMMn/gpg_home --keyid-format 0xlong --batch --receive-keys 4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC" returned non-zero exit status 2
>

**Comment by hartwork** [comment]
> This might be the answer: http://docs.python-requests.org/en/master/community/faq/
> My python is 2.7.6 I am upgrading now.

I see, thanks!

About the GPG error, I think that's temporary and a keyserver/network problem. I could mate it try multiple times. I could also drop the idea of fetching at least one key from the network. Give me a second.

**Comment by hartwork** [comment]
> I could also drop the idea of fetching at least one of the keys from the web

Done, please try again.

**Comment by danst0** [comment]
Thank you very much. Seems to move forward... now:

> Keys found allowed to sign archlinux-keyring tarball:
>   - Bartlomiej Piotrowski <bpiotrowski@archlinux.org> (F3691687D867B81B51CE07D9BBE43771487328A9)
>   - Christian Hesse <Christi@n-Hes.se> (BD84DE71F493DF6814B0167254EDC91609BC9183)
>   - Evangelos Foutras <evangelos@foutrelis.com> (86CFFCA918CF3AF47147588051E8B148A9999C34)
>   - Pierre Schmitz <pierre@archlinux.de> (4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC)
>   - Thomas Bächler <thomas@bchlr.de> (A314827C4E4250A204CE6E13284FC34C8E4B1A25)
> Importing GPG keys from the internet...
> Importing GPG keys from disk...
> Verifying integrity of file "/var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz"...
> Cleaning up "/tmp/tmpREWG_q"...
> Unmounting partitions...
> Removing directory "/mnt/tmpOZWf_p"...
> Deactivating partition devices...
> Traceback (most recent call last):
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
>     main_function(messenger, options)
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/cli.py", line 93, in _main__level_three
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 927, in run
>     self.run_directory_bootstrap()
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 420, in run_directory_bootstrap
>     self._config.bootloader_approach,
>   File "build/bdist.linux-x86_64/egg/image_bootstrap/distros/arch.py", line 76, in run_directory_bootstrap
>     bootstrap.run()
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 327, in run
>     self._import_gpg_keyring(abs_temp_dir, abs_gpg_home_dir, package_filename, package_yyyymmdd)
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 139, in _import_gpg_keyring
>     self._import_gpg_key_file(abs_gpg_home_dir, abs_archlinux_gpg_path)
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 131, in _import_gpg_key_file
>     self._executor.check_call(cmd)
>   File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/executor.py", line 23, in check_call
>     cwd=cwd,
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['unshare', '--fork', '--pid', 'gpg', '--home', '/tmp/tmpREWG_q/gpg_home', '--keyid-format', '0xlong', '--batch', '--quiet', '--import', '/tmp/tmpREWG_q/archlinux-keyring-20180108/archlinux.gpg']' returned non-zero exit status 2
> Error: Command "unshare --fork --pid gpg --home /tmp/tmpREWG_q/gpg_home --keyid-format 0xlong --batch --quiet --import /tmp/tmpREWG_q/archlinux-keyring-20180108/archlinux.gpg" returned non-zero exit status 2
> If this looks like a bug to you, please file a report at https://github.com/hartwork/image-bootstrap.  Thank you!
>

**Comment by hartwork** [comment]
Can you add `--verbose` to see error output from GPG?

**Comment by danst0** [comment]
No problem:
`Importing GPG keys from the internet...
Importing GPG keys from disk...
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /home/daniel/.python-eggs/image_bootstrap-0.9.2.1-py2.7.egg-tmp/directory_bootstrap/resources/arch/BD84DE71F493DF6814B0167254EDC91609BC9183.asc
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /home/daniel/.python-eggs/image_bootstrap-0.9.2.1-py2.7.egg-tmp/directory_bootstrap/resources/arch/86CFFCA918CF3AF47147588051E8B148A9999C34.asc
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /home/daniel/.python-eggs/image_bootstrap-0.9.2.1-py2.7.egg-tmp/directory_bootstrap/resources/arch/4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC.asc
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /home/daniel/.python-eggs/image_bootstrap-0.9.2.1-py2.7.egg-tmp/directory_bootstrap/resources/arch/A314827C4E4250A204CE6E13284FC34C8E4B1A25.asc
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /home/daniel/.python-eggs/image_bootstrap-0.9.2.1-py2.7.egg-tmp/directory_bootstrap/resources/arch/F3691687D867B81B51CE07D9BBE43771487328A9.asc
Verifying integrity of file "/var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz"...
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --verify /var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz.sig /var/cache/directory-bootstrap/archlinux-keyring-20180108.tar.gz
gpg: Signature made Mo 08 Jan 2018 05:37:20 CET
gpg:                using RSA key 0xBBE43771487328A9
gpg: Good signature from "Bartlomiej Piotrowski <b@bpiotrowski.pl>"
gpg:                 aka "Bartłomiej Piotrowski <b@bpiotrowski.pl>"
gpg:                 aka "Bartłomiej Piotrowski <bpiotrowski@archlinux.org>"
gpg:                 aka "Bartlomiej Piotrowski (Barthalion) <barthalion@gmail.com>"
gpg:                 aka "Bartłomiej Piotrowski (Barthalion) <barthalion@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F369 1687 D867 B81B 51CE  07D9 BBE4 3771 4873 28A9
# unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /tmp/tmppT28A0/archlinux-keyring-20180108/archlinux.gpg
gpg: key 0x6BC26A17B9B7018A: no valid user IDs
gpg: key 0xEEEEE2EEEE2EEEEE: no valid user IDs
Cleaning up "/tmp/tmppT28A0"...
Unmounting partitions...
# umount /mnt/tmp86aPrP
Removing directory "/mnt/tmp86aPrP"...
Deactivating partition devices...
# kpartx -d /dev/sdb
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
    main_function(messenger, options)
  File "build/bdist.linux-x86_64/egg/image_bootstrap/cli.py", line 93, in _main__level_three
    bootstrap.run()
  File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 927, in run
    self.run_directory_bootstrap()
  File "build/bdist.linux-x86_64/egg/image_bootstrap/engine.py", line 420, in run_directory_bootstrap
    self._config.bootloader_approach,
  File "build/bdist.linux-x86_64/egg/image_bootstrap/distros/arch.py", line 76, in run_directory_bootstrap
    bootstrap.run()
  File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 327, in run
    self._import_gpg_keyring(abs_temp_dir, abs_gpg_home_dir, package_filename, package_yyyymmdd)
  File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 139, in _import_gpg_keyring
    self._import_gpg_key_file(abs_gpg_home_dir, abs_archlinux_gpg_path)
  File "build/bdist.linux-x86_64/egg/directory_bootstrap/distros/arch.py", line 131, in _import_gpg_key_file
    self._executor.check_call(cmd)
  File "build/bdist.linux-x86_64/egg/directory_bootstrap/shared/executor.py", line 23, in check_call
    cwd=cwd,
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['unshare', '--fork', '--pid', 'gpg', '--home', '/tmp/tmppT28A0/gpg_home', '--keyid-format', '0xlong', '--batch', '--quiet', '--import', '/tmp/tmppT28A0/archlinux-keyring-20180108/archlinux.gpg']' returned non-zero exit status 2
Error: Command "unshare --fork --pid gpg --home /tmp/tmppT28A0/gpg_home --keyid-format 0xlong --batch --quiet --import /tmp/tmppT28A0/archlinux-keyring-20180108/archlinux.gpg" returned non-zero exit status 2

`

**Comment by hartwork** [comment]
My guess would be that `gpg` is GnuPG 1.x rather than 2.x for you? (Idea from https://superuser.com/a/1131072). These versions work for me, same files:
```
# gpg --version | head -n2
gpg (GnuPG) 2.2.4
libgcrypt 1.8.2
```
PS: What's you host's Linux distribution version?

**Comment by danst0** [comment]
I am on Ubuntu 16.04.3 LTS. I do have gpg2 installed... but also gpg

**Comment by danst0** [comment]
I just symlinked gpg2 to gpg. now it seems to run through.

**Comment by hartwork** [comment]
Okay cool. I'll close this ticket as fixed then.

**Comment by hartwork** [comment]
PS: If support for command "gpg2" matters to you, please make a new ticket requesting GPG command autodetection.
