### ISSUE TITLE
Missing paths in $PATH on archlinux

### ISSUE THREAD

**Issue by leophys** [hartwork/image-bootstrap#62]
Hi,
first of all, thank you for the work! It's a very handy and nice tool.

Second, the *bug*: in Arch Linux the default `$PATH` only has `/usr/local/sbin`, `/usr/local/bin`, and `/usr/bin`. When chrooting, such `$PATH` is preserved. Some of the needed executables in debian are under `/usr/sbin`.

The fix is easy as

```
$ sudo PATH=$PATH:/usr/sbin:/bin:/sbin image-bootstrap ...
```

but maybe you could add a check at init time :)

Greetings

**Comment by hartwork** [comment]
Hi!

Which binaries are affected? They are not in `$PATH` even for root / with sudo?

**Comment by hartwork** [comment]
PS: Is the host Debian and the chroot Arch or the other way around?

**Comment by leophys** [comment]
Hi, 
I encountered `chpasswd` and `grub-install` before using the trick above :)
I obviously launched `image-bootstrap` with `sudo`, but `sudo` passes the environment variables of the caller on.
I didn't try to `su -c image-bootstrap`, but `su -c 'echo $PATH'` gives the same `$PATH` as my user...

**Comment by leophys** [comment]
> PS: Is the host Debian and the chroot Arch or the other way around?
The host is Arch and the guest is Debian (stretch)

**Comment by hartwork** [comment]
Confirming weird Arch path over here. What the h***? :smile: 
```
# env -i bash -c 'sed "s,:,\n,g" <<<"$PATH"'
/usr/local/sbin
/usr/local/bin
/usr/bin
```

**Comment by leophys** [comment]
Yup :wink:

**Comment by hartwork** [comment]
With these symlinks on Arch it's clear now why `/usr/bin` does not need to be in `$PATH`:
```
# ls -l /bin /sbin /usr/sbin
lrwxrwxrwx 1 root root 7 Oct 17 07:32 /bin -> usr/bin
lrwxrwxrwx 1 root root 7 Oct 17 07:32 /sbin -> usr/bin
lrwxrwxrwx 1 root root 3 Oct 17 07:32 /usr/sbin -> bin
```

**Comment by hartwork** [comment]
This i Gentoo:
```
# env -i bash -c 'sed "s,:,\n,g" <<<"$PATH"'
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
```

**Comment by hartwork** [comment]
I agree that it would make sense to extend `$PATH` from inside image-bootstrap.

**Comment by hartwork** [comment]
Looking at it now. If you're in the middle of a pull request, now would be a good time to say :smile:

**Comment by leophys** [comment]
On 28 March 2018 21:20:17 CEST, Sebastian Pipping <notifications@github.com> wrote:
>Looking at it now. If you're in the middle of a pull request, now would
>be a good time to say :smile: 

Nope. I can take a look, but you're probably much faster 😬

-- 
Blallo

**Comment by hartwork** [comment]
@leophys could you give Git `master` a try?

**Comment by leophys** [comment]
Success!

Thank you :blush:
