### ISSUE TITLE
Jessie images created on a Stretch host not bootable

### ISSUE THREAD

**Issue by nachtgeist** [hartwork/image-bootstrap#68]
I got bitten by the same effect that was described in #44 (only that I'm using grub, which isn't the core problem however). Jessie's e2fsck simply doesn't know how to handle EXT4's metadata_csum feature (which get's enabled by the Stretch host's mkfs.ext4 by default now) and so the e2fsck on boot fails. Entering the rootpw or pressing CTRL-D both lead to a reboot.

I needed a quick fix, so I didn't spend any time to investigate which of the other, older distributions suffer the same issue as well. Thus, I'm a little hesitant to open a PR for my hack. So here's just a link for now. If further distro/release combos are determined to stumble over this, the if statement in the patch should probably become a function.

https://github.com/nachtgeist/image-bootstrap/commit/f187c99d15d249673972a10046e81c0706d688bc

**Comment by hartwork** [comment]
Hi @nachtgeist ,

thanks for sharing your workaround. jessie is Debian oldstable. I've seen companies from inside that use things like Debian oldstable and older but that's crazy in my world (and even crazy in theirs). I'll drop support for jessie and older official soon (see #69).

Best, Sebastian

**Comment by hartwork** [comment]
I started writing a less hacky patch an the noticed: We can probably(?) only append `-O metadata_csum` if we know the host/building systems mkfs.ext4 understands it. Any ideas how to ensure it does so we don't break e.g. building jessie from jessie?

**Comment by nachtgeist** [comment]
Thanks for the quick fix! Just tested it and it works.

> Any ideas how to ensure it does so we don't break e.g. building jessie from jessie?

I'm not quite sure if that's worth the effort (from my personal perspective a definite no). IMHO the main use case is to be able to build images of older distros from a current host in order to be able to test (or in case of enterprise environments: run :) ) stuff on an older system. Moreover, seeing #69, this workaround can be put to rest anyway, once Jessie has become oldoldstable after Bullseye has been released.

**Comment by hartwork** [comment]
> Thanks for the quick fix! Just tested it and it works.

Excellent, thank you!

**Comment by hartwork** [comment]
With #70 merged, I'll close this ticket as fixed.
