### ISSUE TITLE
_abs_cache_dir 0755

### ISSUE THREAD

**Issue by Buglouse** [hartwork/image-bootstrap#76]
Is this a permission error for the cache directory?
[log.txt](https://github.com/hartwork/image-bootstrap/files/2897698/log.txt)

**Comment by hartwork** [comment]
Python complains about a syntax error so it's not a permission problem. I can see a syntax error at that place and these lines are run every day and are unchanged for three years. 
I noticed though that you're running Python 3 while image-bootstrap is targetting 2.7 as of today. Please execute with Python 2 instead for now and report back if that fixes the problem. Thank you!

**Comment by Buglouse** [comment]
Perfect.
python2.7
