### ISSUE TITLE
ArchLinux Pacman Timeout

### ISSUE THREAD

**Issue by Buglouse** [hartwork/image-bootstrap#77]
Sometimes with Arch build Pacman fails to gather a package:
```
error: failed retrieving file 'python2-2.7.15-4-x86_64.pkg.tar.xz' from mirror.rackspace.com : Connection timed out after 10001 milliseconds
warning: failed to retrieve some files
```
Which results in the exit code:
```
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```
Terminating image-bootstrap. A retry with pacman or increase the timeout?

**Comment by hartwork** [comment]
Hi!

I'm not sure if retrying with the same mirror has much chance to succeed the second time, mor or less the same for increasing the timeout beyond 10 seconds. In an enterprise context, I'd propose a local mirror and using that for a reliable, speedy source to fetch from. Keeping that mirror in sync then would be out of image-bootstrap's scope and could work asynchronously.

Either way, if that mirror is not a good stable choice from your location, maybe using a different mirror URL already solves the problem?:
```console
# image-bootstrap arch --help
usage: image-bootstrap arch [-h] [--arch {i686,x86_64}]
                            [--image-date YYYY-MM-DD] [--mirror URL]

optional arguments:
  -h, --help            show this help message and exit
  --arch {i686,x86_64}  architecture (e.g. x86_64)
  --image-date YYYY-MM-DD
                        date to use boostrap image of (e.g. 2015-05-01,
                        default: latest available)
  --mirror URL          pacman mirror to use (default:
                        http://mirror.rackspace.com/archlinux/$repo/os/$arch)
```
What do you think?

**Comment by Buglouse** [comment]
Usin the enterprise solution is not applicable for this application, but would work fine in that environment.
Switching mirrors should be sufficient for the time being, thanks.
