### ISSUE TITLE
Arch install-cloud-init-0-7-6.sh sudo

### ISSUE THREAD

**Issue by Buglouse** [hartwork/image-bootstrap#79]
I get this for Arch build:
```
# sudo -u nobody makepkg
sudo: unable to stat /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**Comment by Buglouse** [comment]
umask or mount option?
chmod 0755 /etc continues
```
error: failed to initialize alpm library
(could not open database: /var/lib/pacman/)
==> ERROR: 'pacman' returned a fatal error (255):
```

**Comment by hartwork** [comment]
This is weird. Is that the latest version from pip or Git master?
It seems like the code from Git master worked fine on the build host this very night, see https://linuximages.de/openstack/arch/ .

**Comment by hartwork** [comment]
Just tried on a Gentoo box: the `sudo -u nobody makepkg` step works without issues. Nightly build host is Debian. What is your host system? I'll need help getting this reproduced.

**Comment by Buglouse** [comment]
I was under the understanding that host system should not affect the bootstrap build.
`Linux 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 unknown unknown GNU/Linux
`

**Comment by hartwork** [comment]
Ideally, it should not but reality sometimes has it's own way :)
Do you have any idea why sudo fails in your environment but not in the two environments I tried? Does it happen every time?

**Comment by Buglouse** [comment]
My umask was set to 0077 in host environment.
Setting umask to 0022 before execution ran a successful build.
