### ISSUE TITLE
Failed to run image-bootstrap with Python 3.5

### ISSUE THREAD

**Issue by vanyaio** [hartwork/image-bootstrap#84]
Got the following error on Ubuntu 16.04 host

$ ./image-bootstrap --help

Traceback (most recent call last):
  File "./image-bootstrap", line 11, in <module>
    from image_bootstrap.__main__ import main
  File "/home/vanya/embedded/image-bootstrap/image_bootstrap/__main__.py", line 21, in <module>
    from image_bootstrap.distros.gentoo import GentooStrategy
  File "/home/vanya/embedded/image-bootstrap/image_bootstrap/distros/gentoo.py", line 12, in <module>
    from directory_bootstrap.distros.gentoo import GentooBootstrapper
  File "/home/vanya/embedded/image-bootstrap/directory_bootstrap/distros/gentoo.py", line 98
    self._messenger.info(f'Selected mirror {mirror_url} .')
                                                                                     ^
SyntaxError: invalid syntax

**Comment by vanyaio** [comment]
It seems like some problem with python versions since now project uses python3 which is not allowed f'String' syntax as far as I am concerned, and before it used to have python2 as I see from https://github.com/hartwork/image-bootstrap/commit/4f0b53aceb5e1ef80d52811bc370e8d1f0341634

**Comment by hartwork** [comment]
The latest release uses f-strings which are Python 3.6+ feature. So I'll need to adjust https://github.com/hartwork/image-bootstrap/blob/master/setup.py#L25 to require Python 3.6+. 
May I ask why are you using Ubuntu 16.04 LTS when there is 18.04 LTS around?
