### ISSUE TITLE
Fail to install package to image?

### ISSUE THREAD

**Issue by tmpm697** [hartwork/image-bootstrap#89]
Steps:
```
> directory-bootstrap arch --arch x86_64 arch
> virt-make-fs -F qcow2 -v arch/ arch.img
> qemu-img resize arch.img +40G

> virt-filesystems --long -h --all -a arch.img
Name      Type        VFS   Label  MBR  Size  Parent
/dev/sda  filesystem  ext2  -      -    753M  -
/dev/sda  device      -     -      -    41G   -

> virt-customize --format qcow2 -a arch.img --run-command 'pacman -S fd' -v
:: Proceed with installation? [Y/n] error: Partition / too full: 22003 blocks needed, 0 blocks free
error: failed to commit transaction (not enough free disk space)
```

I want to install `fd` package to image, I resize image to plus 40G, why I can still install pacakge to image?

**Comment by hartwork** [comment]
Hi!

`directory-bootstrap` creates chroots, `image-boostrap` creates VM images. You seem to use the chroot tool to get a VM image in the end using `virt-*` commands that I am not familiar with, yet. My superficial impression is that you don't resize the first partition and also do not resize the file system on it hence there is no space despite disk resize. That seems needed in your case but I'm only guessing. If you need help beyond that please describe your scenario with more context and detail on or off GitHub. Thanks!

Best, Sebastian

**Comment by tmpm697** [comment]
Thanks for reply. 

directory-bootstrap does not allow me to install some custom packages into the image, so I use virt-customize to install somes. 

Problem is that either I want to install more packages using virt-customize or not I would need to have more disk at some points soon when create a vm fromt that image, so I think increasing it first as virtual disk in image rather than each time running a vm.

So how to install custom packages with directory-bootstrap or resize image’s disk correctly?

**Comment by hartwork** [comment]
> directory-bootstrap does not allow me to install some custom packages into the image, so I use virt-customize to install somes.

`directory-bootstrap` creates a chroot folders that you can install things in using plain `chroot` or tools like https://github.com/pkgcore/pychroot that take all the bind mount setup off your shoulders. So chroot creation has not need script hooks so far unlike `image-boostrap` where `--scripts-pre` and its two siblings allow installation of additional packages.

> Problem is that either I want to install more packages using virt-customize or not I would need to have more disk at some points soon when create a vm from that image, so I think increasing it first as virtual disk in image rather than each time after running a vm.
> 
> So how to install custom packages with directory-bootstrap or resize image’s disk correctly?

There is still a lot unclear to me about your scenario. Do you have OpenStack and cloud-init in your scenario? The later increases sizes on the fly during first boot of the VM using a tool called `growpart`.

**Comment by hartwork** [comment]
> The actual effort is actually [here](https://github.com/dmacvicar/terraform-provider-libvirt/issues/754). As I want to create an image and spin up a vm from it using terraform-provider-libvirt

PS: I'm not familiar with terraform-provider-libvirt but if you're sure you need EFI https://blog.hartwork.org/posts/get-qemu-to-boot-efi/ may help.

**Comment by tmpm697** [comment]
Yes, growpart seems to be the right tool, thanks for mention, but it from aur not official repos. 

To boot efi, we need to specify -bios option, I’m trying to pass it to terraform-provider-libvirt.

**Comment by hartwork** [comment]
> Yes, growpart seems to be the right tool, thanks for mention, but it from aur not official repos.

It's one way but you can achieve the same using parted and so.


> To boot efi, we need to specify -bios option, I’m trying to pass it to terraform-provider-libvirt.

I think you can replace `-bios` with `-drive` if you pass the right values to it: It worked for me before. Maybe that works better in integration if `-bios` is unsupported. I wonder if you really need EFI in a VM — I would "bet" you don't but just a guess.

I think we're quite far from a bug report on `image-bootstrap` by now. If you need more help with this, please find my mail and let's move to Google Hangout or something with voice. Good luck.

**Comment by tmpm697** [comment]
Thanks, I’d like to have more confirms as I’m not at pc right now.

1. You can chroot to folder after directory-boostrap command to install packages of choice?

2. You can specify to directory-bootstrap to use EFI or MBR?

**Comment by hartwork** [comment]
> Thanks, I’d like to have more confirms as I’m not at pc right now.
> 
>     1. You can chroot to folder after directory-boostrap command to install packages of choice?

Yes. This worked for me, plain `chroot` and bind mounts:

```bash
virtualenv --python=python3.7 py37
source py37/bin/activate
pip install image-bootstrap
sudo $(which directory-bootstrap) --debug --verbose arch arch_chroot
mkdir arch_chroot_proxy
sudo mount --bind arch_chroot arch_chroot_proxy  # to fool pacman checks for its / mount location
sudo mount --bind /proc arch_chroot_proxy/proc
sudo cp /etc/resolv.conf arch_chroot_proxy/etc/  # for internet access
sudo chroot arch_chroot_proxy pacman-key --populate archlinux || echo "failed, that's okay"  # workaround against pacman "error: GPGME error: Invalid crypto engine"
sudo lsof | fgrep "$PWD/arch_chroot_proxy" | awk '{print $2}' | sort -u | xargs -r -t sudo kill  # kill gpg-agent leftover
sudo chroot arch_chroot_proxy pacman --noconfirm -S nano ; echo $?
mount | fgrep "on $PWD" | awk '{print $3}' | sort -r | xargs -r -t sudo umount
```
Need to fool pacman with a proxy bind mount seems to be something new.


>     2. You can specify to directory-bootstrap to use EFI or MBR?

directory-bootstrap and does not care about VMs, booting, BIOSes — just about creating a chroot.
